<?php
/**
 * Yireo Deleteanyorder for Magento 
 *
 * @package     Yireo_DeleteAnyOrder
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright 2015 Yireo (http://www.yireo.com/)
 * @license     Open Source License
 */
?>
<?php
$orders = $this->getOrders();
$header = $this->__('Confirmation');
?>
<div class="content-header">
<table cellspacing="0">
	<tr>
		<td style="width:40%;"><h3 class="icon-head head-tag"><?php echo $this->getHeader($header); ?></h3></td>
        <td class="formbuttons" align="right">
            <?php echo $this->getChildHtml('back_button'); ?>
            <?php echo $this->getChildHtml('delete_button'); ?>
        </td>
	</tr>
</table>
</div>

<form action="<?php echo $this->getDeleteUrl() ?>" method="post" id="deleteanyorder_confirm_form" enctype="multipart/form-data">
<?php foreach($orders as $order) { ?>
<input type="hidden" name="order_ids[]" value="<?php echo $order->getId(); ?>" />
<?php } ?>
<?php echo $this->getBlockHtml('formkey')?>
</form>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo $this->__('Order'); ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list" width="100%">
            <tr>
                <th width="150"><?php echo $this->__('Order'); ?></th>
                <th width="200"><?php echo $this->__('Customer'); ?></th>
                <th width="100">&nbsp;</th>
                <th width="150"><?php echo $this->__('Purchased on'); ?></th>
                <th width="150"><?php echo $this->__('Amount'); ?></th>
                <th><?php echo $this->__('Status'); ?></th>
            </tr>
            <?php foreach($orders as $order) { ?>
            <tr>
                <td># <?php echo $order->getIncrementId(); ?></td>
                <td colspan="2"><?php echo $order->getCustomerFirstname(); ?> <?php echo $order->getCustomerLastname(); ?></td>
                <td><?php echo $order->getCreatedAt(); ?></td>
                <td><?php echo $order->formatPrice($order->getBaseGrandTotal()); ?></td>
                <td><?php echo $order->getState(); ?></td>
            </tr>
            <tr>
                <td colspan="2">&nbsp;</td>
                <td colspan="4">
                    <div class="grid np" style="margin-bottom: 5px; border-bottom: 1px solid #c3c3c3">
                    <div class="hor-scroll">
                    <table cellspacing="0" class="data order-tables">
                        <thead>
                        <tr class="headings">
                            <th><?php echo $this->__('ID'); ?></td>
                            <th><?php echo $this->__('Item'); ?></td>
                            <th><?php echo $this->__('SKU'); ?></td>
                            <th><?php echo $this->__('Price'); ?></td>
                        </tr>
                        </thead>
                        <tbody class="even">
                        <?php foreach($order->getItemsCollection() as $item) { ?>
                        <tr class="border">
                            <td><?php echo $item->getId(); ?></td>
                            <td><?php echo $item->getName(); ?></td>
                            <td><?php echo $item->getSku(); ?></td>
                            <td><?php echo $order->formatPrice($item->getPrice()); ?></td>
                        </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    </div>
                    </div>
                </td>
            </tr>
            <?php } ?>
        </table>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    var deleteanyorderForm = new varienForm('deleteanyorder_confirm_form');
</script>
